### ISSUE TITLE
整合steam进入咩auth

### ISSUE THREAD

**Issue by NatsumiXD** [zanjie1999/meUiharu-miBand7-Watchface#1]
这个是已经实现的代码https://github.com/chrisxue815/steam-auth-code

**Comment by NatsumiXD** [comment]
这里有一篇思路 https://www.cnblogs.com/OoGKoO/p/14824595.html

**Comment by zanjie1999** [comment]
咩咩写好了，但是咩咩发现他必须async才能调用那两条await的api，可能需要使用其他方式手动实现这个加密  
https://github.com/zanjie1999/steam-auth-js/blob/main/steam-auth-js.js

**Comment by NatsumiXD** [comment]
> 咩咩写好了，但是咩咩发现他必须async才能调用那两条await的api，可能需要使用其他方式手动实现这个加密  
> https://github.com/zanjie1999/steam-auth-js/blob/main/steam-auth-js.js

其他方式（？
miband不能async的嘛（

**Comment by zanjie1999** [comment]
quickjs环境有没有crypto，需要重新实现
如果有什么奇怪的骚操作，那这已经超出我的知识范围了（
