### ISSUE TITLE
Love to see an English version

### ISSUE THREAD

**Issue by schroef** [zanjie1999/meUiharu-miBand7-Watchface#2]
Im interested in making an English version of this?
Would it be possble?

**Comment by zanjie1999** [comment]
In fact, this watchface supports Simplified Chinese, Traditional Chinese and English, but only Chinese is enabled.

**Comment by zanjie1999** [comment]
https://github.com/zanjie1999/meUiharu-miBand7-Watchface/releases/tag/12.0
All functions now support English

**Comment by schroef** [comment]
Wow nice! Need to find method for installing now. The trick i see on internet doesn't work anymore. The trick was to download a watchfaces, then replace the content in the watch_face_local folder.

Do you happen to have a working method?

**Comment by zanjie1999** [comment]
I use AmazTool on iOS, or replace zepplife download watchface file in `/data/data/com.xiaomi.hm.health/files/watch_skin_local` on Android (need root permission), or use old version zepplife app on Android and replace watchface file in `/sdcard/Adnroid/data/com.xiaomi.hm.health/files/watch_skin_local` (no need root permission)
