### ISSUE TITLE
咩咩呀 meAuth的界面高度不对吧，下边多了点，往上拖会动一点

### ISSUE THREAD

**Issue by zjlloveo0** [zanjie1999/meUiharu-miBand7-Watchface#3]
我想看源码来着，但好像看到经历了什么曲折😮‍💨

**Comment by zanjie1999** [comment]
这是系统bug，屏幕高度是490但是小程序的画布最大是480，表盘是正常的490，咩Auth的独立小程序是直接从表盘里复制出来的，为了保证代码的可合并性，就没改

**Comment by zanjie1999** [comment]
昨天的系统更新似乎修复了这个bug

**Comment by zjlloveo0** [comment]
> 昨天的系统更新似乎修复了这个bug

感谢提醒呀，不过已经改了咩咩的表盘用啦，很好用👍
